version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:8u141
     steps:
            - checkout
            - run: ./gradlew clean build
            - run: ./gradlew -Pprofile=springnext clean build
general:
  branches:
    ignore:
      - gh-pages # list of branches to ignore

dependencies:
  cache_directories:
    - "~/.m2"
