version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u141
    steps:
      - checkout
      - run: ./gradlew clean build
      - run: ./gradlew -Pprofile=spring4-next clean build

general:
  branches:
    ignore:
      - gh-pages # list of branches to ignore
